#!/bin/sh
set -e

if [ -z "$1" ]; then
	echo "Usage: $0 /dev/whatever"
	exit 1
fi
disk="$1"
root=`mktemp -d`

mount /dev/mapper/LINK-rootfs -t btrfs -o compress,ssd "$root"
mkdir -p "$root/boot"
mount /dev/mapper/LINK-boot -t ext2 "$root/boot"
mkdir -p "$root/home"
mount /dev/mapper/LINK-home -t ext4 "$root/home"

debootstrap --arch amd64 --components 'main,contrib,non-free' squeeze "$root" http://http.us.debian.org/debian

mount --bind /dev      "$root/dev"
mount --bind /dev/pts  "$root/dev/pts"
mount --bind /dev/shm  "$root/dev/shm"
mount --bind /proc     "$root/proc"
mount --bind /sys      "$root/sys"

cp setup-debian "$root/root/"
cp debconf-seed "$root/root/"
cp archive-keys "$root/root/"
cp asound-state "$root/root/"
chmod +x "$root/root/setup-debian" # just in case

set +e # clean up even if setup fails
if ! chroot "$root" /root/setup-debian "$disk" ; then
	echo "# SETUP HAS FAILED US. Sending you in to check..."
	chroot "$root" /bin/bash -i
fi
umount "$root/dev/pts"
umount "$root/dev/shm"
umount "$root/dev"
umount "$root/sys"
umount "$root/proc"
umount "$root/home"
umount "$root/boot"
umount "$root"
set -e

rmdir "$root"
