#!/bin/sh

if [ -z "$1" ]; then
	echo "Usage: $0 /dev/whatever"
	exit 1
fi
disk="$1"
root=`mktemp -d`

mount /dev/mapper/LINK-rootfs "$root"
mkdir -p "$root/home"
mount /dev/mapper/LINK-home "$root/home"

debootstrap --arch amd64 --components 'main,contrib,non-free' squeeze "$root" http://http.us.debian.org/debian

mount --bind /dev      "$root/dev"
mount --bind /dev/pts  "$root/dev/pts"
mount --bind /dev/shm  "$root/dev/shm"
mount --bind /proc     "$root/proc"
mount --bind /sys      "$root/sys"

exit
cp setup-debian "$root/root"
chmod +x "$root/root/setup-debian" # just in case
chroot "$root" /root/setup-debian "$disk"

umount "$root/dev/pts"
umount "$root/dev/shm"
umount "$root/dev"
umount "$root/sys"
umount "$root/proc"
umount "$root/home"
umount "$root"
rmdir "$root"
