#!/bin/sh

if [ -z "$1" ]; then
	echo "Usage: $0 /dev/whatever"
	exit 1
fi

disk="$1"
part="${1}1"

echo "About to destroy all data on $1; control-C to abort!"
sleep 5

echo "Too late! Going ahead..."
echo ',,L,*' | sfdisk --DOS "$disk"

pvcreate "$part"
vgcreate LINK "$part"
lvcreate -L 1g -n 'rootfs' LINK
lvcreate -L 512m -n 'home' LINK

for lv in LINK-rootfs LINK-home; do
	mkfs.ext4 \
		-E lazy_itable_init=1 -L LINK-ROOTFS \
		-O dir_index,filetype,flex_bg,extent,uninit_bg,resize_inode,sparse_super \
		/dev/mapper/$lv
done

# Silly to reserve space for root on a random user's home dir
tune2fs -r 0 /dev/mapper/LINK-home
