#!/bin/sh
set -e

if [ -z "$1" ]; then
	echo "Usage: $0 /dev/whatever"
	exit 1
fi

disk="$1"
part="${1}1"

echo "About to destroy all data on $1; control-C to abort!"
sleep 5

echo "Too late! Going ahead..."
echo ',,L,*' | sfdisk --DOS "$disk"

dd if=/dev/zero of="$part" bs=512 count=1

pvcreate "$part"
vgcreate LINK "$part"
lvcreate -L 48m -n 'boot' LINK
lvcreate -L 1g -n 'rootfs' LINK
lvcreate -L 512m -n 'home' LINK
